# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

services:
    nkg.poll:
        class: nkgPollBundle\Services\PollService
        arguments:
            - @doctrine.orm.entity_manager
    nkg.opinion:
        class: nkgPollBundle\Services\OpinionService
        arguments:
            - @doctrine.orm.entity_manager
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
